# Generated by Django 5.0.6 on 2025-02-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0027_alter_source_sponsorblock_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='season',
            field=models.SmallIntegerField(default=1, editable=False, help_text='Season number that will be used for playlist', verbose_name='season'),
        ),
    ]
