# Generated by Django 5.0.6 on 2025-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0028_source_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='season',
            field=models.SmallIntegerField(default=1, help_text='Season number that will be used for playlist', verbose_name='season'),
        ),
    ]
